Fix: Resolve type errors in hooks
The following errors were resolved:
- `src/hooks/useFerramentas.ts(36,37)`: Property 'saiu' does not exist on type.
- `src/hooks/useFuncionarios.ts(36,15)`: Type 'string | number | true | { [key: string]: Json; } | Json[]' is not assignable to type 'any[]'.